baseURL = "http://www.yuhengchen.com/"
DefaultContentLanguage = "zh" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "zh"
title = "Skyline Artifact"
copyright = "2020 skyfact"
theme = "diary"
# googleAnalytics = "UA-123-45"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "monokai"
    tabWidth = 4

[params]
subtitle = "skyfact"
#enableGitalk = true

disableDarkMode=true

favicon="/favicon.ico"

# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "Skyline Artifact" # will set 'og:site_name'
description = "My HomePage Description"  # will set 'og:description'

#[params.gitalk]
#  owner = "user"
#  repo = "repo name"
#  client_id = "your client id"
#  client_secret = "your client secret"
[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
url = "/posts"
name = "博客"
weight = 1
[[menu.main]]
url = "/categories"
name = "分类"
weight = 2
[[menu.main]]
url = "/tags"
name = "标签"
weight = 3
#[[menu.main]]
#url = "/index.xml"
#name = "RSS Feed"
#weight = 4
